import Head from "next/head";

import styles from "../styles/app.module.css";

import Header from "../components/Header";
import Footer from "../components/Footer";
import GebaudeCard from "../components/GebaudeCard";

const gebauedeData = [
  {
    id: "bierpinsel",
    name: "Bierpinsel",
    architekt: [
      {
        name: "Ralf Schüler",
        link: "https://de.wikipedia.org/wiki/Ralf_Sch%C3%BCler_und_Ursulina_Sch%C3%BCler-Witte"
      },
      {
        name: "Ursulina Schüler-Witte",
        link: "https://de.wikipedia.org/wiki/Ralf_Sch%C3%BCler_und_Ursulina_Sch%C3%BCler-Witte"
      }
    ],
    bauzeit: "1972—1976",
    karte: "https://goo.gl/maps/SmF6s46hufEq6TfHA",
    wiki: "https://www.abandonedberlin.com/bierpinsel",
    modelId: "debea999b02f4393a3b8d721a573eab7"
  }
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.wrapper}>
        <Header />

        <section className={styles.cards}>
          {gebauedeData.map((gebauede) => (
            <GebaudeCard
              key={gebauede.id}
              id={gebauede.id}
              name={gebauede.name}
              architekt={gebauede.architekt}
              bauzeit={gebauede.bauzeit}
              karte={gebauede.karte}
              wiki={gebauede.wiki}
              modelId={gebauede.modelId}
            />
          ))}
        </section>

        <Footer />
      </main>
    </div>
  );
}
